CREATE table trade_days(
    id int(11) unsigned not null auto_increment comment '主键',
    exchange varchar(16) not null comment '交易所 SSE上交所 SZSE深交所',
    cal_date varchar(16) not null comment '日历日期',
    is_open varchar(16) not null comment '是否交易 0休市 1交易',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 comment '交易日历';


create table stock_info(
    id int(11) unsigned not null auto_increment comment '主键',
    code varchar(16) not null comment '',
    industry_name varchar(16) comment '所属行业',
    industry_code varchar(16) comment '',
    market_tplus varchar(16) comment '',
    symbol varchar(16) comment '',
    special_type varchar(16) comment '',
    exchange varchar(16) comment '',
    status varchar(16) comment '',
    type varchar(16) comment '',
    listed_date varchar(16) comment '',
    de_listed_date varchar(16) comment '',
    sector_code_name varchar(16) comment '',
    abbrev_symbol varchar(16) comment '',
    sector_code varchar(16) comment '',
    round_lot varchar(16) comment '',
    trading_hours varchar(16) comment '',
    board_type varchar(16) comment '',
    industry_name varchar(16) comment '',
    trading_code varchar(16) comment '',
    fullname varchar(16) comment '',
    area varchar(16) comment '',
    province varchar(20) comment '省份',
    created_datetime varchar(30) comment '创建时间',
    update_datetime varchar(30) comment '更新时间',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 comment '';

create table stock_basic(
    id int(11) unsigned not null auto_increment comment'主键',
    code varchar(16) not null comment '股票代码',
    symbol varchar(16) not null comment '股票名称',
    fullname varchar(128) comment '中文名',
    enname varchar(128) comment '英文全称',
    cnspell varchar(64) comment '拼音缩写',
    area varchar(20) comment '地域',
    province varchar(20) comment '省份',
    address varchar(128) comment '地址',
    industry_name varchar(16) comment '所属行业',
    industry_code varchar(16) comment '所属行业',
    sector_code_cn varchar(16) comment '所属行业',
    board_type varchar(16) comment '板块类型（主板/创业板/科创板/CDR）',
    exchange varchar(16) comment '交易所代码',
    curr_type varchar(16) comment '交易货币',
    status varchar(16) comment '上市状态 ’Active’ - 正常上市, ‘Delisted’ - 终止上市, ‘TemporarySuspended’ - 暂停上市,',
    listed_date varchar(16) comment '上市日期',
    de_listed_date varchar(16) comment '退市日期',
    created_datetime varchar(30) comment '创建时间',
    update_datetime varchar(30) comment '更新时间'
);

CREATE table listed_stock_info_ext(
    id int(11) unsigned not null auto_increment comment '主键',
    code varchar(16) not null comment '股票代码',
    symbol varchar(16) not null comment '股票名称',
    area varchar(16) comment '股票区域',
    industry varchar(16) comment '所属行业',
    list_date varchar(16)  comment '上市日期',
    trade_date varchar(16) comment '交易日期',
    pe float not null default '0.0' comment '市盈率（动）',
    float_share float not null default '0.0' comment '流通股本（万）',
    total_share float not null default '0.0' comment '总股本（万）',
    total_assets float not null default '0.0' comment '总资产（万）',
    liquid_assets float not null default '0.0' comment '流动资产（万）',
    fixed_assets float not null default '0.0' comment '固定资产（万）',
    reserved float not null default '0.0' comment '公积金',
    reserved_pershare float not null default '0.0' comment '每股公积金',
    eps float not null default '0.0' comment '每股收益',
    bvps float not null default '0.0' comment '每股净资产',
    pb float not null default '0.0' comment '市净率',
    undp float not null default '0.0' comment '未分配利润',
    per_undp float not null default '0.0' comment '每股未分配利润',
    rev_yoy float not null default '0.0' comment '收入同比（%）',
    profit_yoy float not null default '0.0' comment '利润同比（%）',
    gpr float not null default '0.0' comment '毛利率（%）',
    npr float not null default '0.0' comment '净利润率（%）',
    holder_num int(11) not null default '0' comment '股东人数',
    update_time datetime default CURRENT_TIMESTAMP not null on update CURRENT_TIMESTAMP comment '更新时间',
    create_time datetime default CURRENT_TIMESTAMP not null comment '创建时间',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 comment '上市股票信额外息表';

--
--
-- create table stock_finance_lrb(
--     id int(11) unsigned not null auto_increment comment'主键',
--     revenue float comment '营业总收入：公司经营所取得的收入总额金融类公司不公布营业总收入，因此 revenue 指标只能使用类似的一个指标-operating_revenue',
--     operating_revenue float comment '营业收入：公司经营主要业务所取得的收入总额',
--     net_interest_income float comment '利息净收入',
--     net_commission_income float comment '利息净收入',
--     commission_income float comment '其中:手续费及佣金收入',
--     commission_expense float comment '其中:手续费及佣金支出',
--     net_proxy_security_income float comment '其中:代理买卖证券业务净收入',
--     sub_issue_security_income float comment '其中:证券承销业务净收入',
--     net_trust_income float comment '其中:受托客户资产管理业务净收入',
--     earned_premiums float comment '已赚保费',
--     premiums_income float comment '保险业务收入',
--
--     report_date varchar(30) comment '报表日期',
-- )

create table index_daily(
    id int(11) unsigned not null auto_increment comment'主键',
    code varchar(16) not null comment '股票代码',
    date varchar(16) not null comment '日期',
    open float comment '开盘价',
    close float comment '收盘价',
    high float comment '收盘价',
    low float comment '收盘价',
    volume float comment '收盘价',
    amount float comment '收盘价'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 comment '指数日线数据';

create table stock_finance_lrb (
    id int(11) unsigned not null auto_increment comment'主键',
    code varchar(16) not null comment '代码',
    revenue float comment '营业总收入：公司经营所取得的收入总额金融类公司不公布营业总收入，因此 revenue 指标只能使用类似的一个指标-operating_revenue',
    operating_revenue float comment '营业收入：公司经营主要业务所取得的收入总额',
    net_interest_income float comment '利息净收入',
    net_commission_income float comment '利息净收入',
    commission_income float comment '其中:手续费及佣金收入',
    commission_expense float comment '其中:手续费及佣金支出',
    net_proxy_security_income float comment '其中:代理买卖证券业务净收入',
    sub_issue_security_income float comment '其中:证券承销业务净收入',
    net_trust_income float comment '其中:受托客户资产管理业务净收入',
    earned_premiums float comment '已赚保费',
    premiums_income float comment '保险业务收入',
    reinsurance_income float comment '其中:分保费收入',
    reinsurance float comment '减:分出保费',
    unearned_premium_reserve float comment '提取未到期责任准备金',
    total_expense float comment '营业总成本',
    operating_expense float comment '营业支出',
    refunded_premiums float comment '退保金',
    compensation_expense float comment '赔付支出',
    amortization_expense float comment '减:摊回赔付支出',
    premium_reserve float comment '提取保险责任准备金',
    amortization_premium_reserve float comment '减:摊回保险责任准备金',
    policy_dividend_payout float comment '保单红利支出',
    reinsurance_cost float comment '分保费用',
    other_operating_revenue float comment '其他经营收入',
    other_operating_cost float comment '其他经营成本',
    r_n_d float comment '研发费用',
    other_net_income float comment '非经营性净收益',
    net_open_hedge_income float comment '净敞口套期收益',
    other_revenue float comment '其他收益',
    gredit_asset_impairment float comment '信用资产减值损失',
    o_n_a_expense float comment '业务及管理费用',
    amortization_reinsurance_cost float comment '减:摊回分保费用',
    insurance_commission_expense float comment '保险手续费及佣金支出',
    disposal_income_on_asset float comment '资产处置收益',
    cost_of_goods_sold float comment '营业成本：公司经营主要业务产生的实际成本',
    sales_tax float comment '营业税',
    gross_profit float comment '主营业务利润',
    selling_expense float comment '销售费用：指企业在销售产品、自制半成品和工业性劳务等过程中发生的各项费用',
    ga_expense float comment '管理费用：指企业的行政管理部门为管理和组织经营而发生的各项费用',
    financing_expense float comment '财务费用',
    financing_interest_income float comment '利息收入',
    financing_interest_expense float comment '利息支出',
    exchange_gains_or_losses float comment '兑汇损益',
    profit_from_operation float comment '营业利润',
    invest_income_associates float comment '对联营合营企业的投资收益',
    fair_value_change_income float comment '公允价值变动净收益',
    investment_income float comment '投资收益',
    asset_impairment float comment '资产减值损失',
    interest_income float comment '利息收入',
    interest_expense float comment '利息支出',
    non_operating_revenue float comment '营业外收入',
    non_operating_expense float comment '营业外支出',
    disposal_loss_on_asset float comment '非流动资产处置净损失',
    other_effecting_total_profits_items float comment '影响利润总额的其他科目',
    profit_before_tax float comment '利润总额',
    income_tax float comment '所得税',
    unrealised_investment_loss float comment '未确认的投资损失',
    other_effecting_net_profits_items float comment '影响净利润的其他科目',
    net_profit float comment '净利润（收益）是指在利润总额中按规定交纳了所得税以后公司的利润留存，一般也称为税后利润或净收入',
    non_recurring_pnl float comment '非经常性损益',
    net_profit_deduct_non_recurring_pnl float comment '扣除非经常性损益后的净利润',
    classified_by_continuity_operation float comment '(一)按经营持续性分类',
    continuous_operation_net_profit float comment '持续经营净利润',
    discontinued_operation_net_profit float comment '终止经营净利润',
    classified_by_ownership float comment '(二)按所有权归属分类',
    net_profit_parent_company float comment '归属母公司净利润',
    minority_profit float comment '少数股东损益',
    other_income float comment '其他综合收益',
    other_income_unclassified_income_statement float comment '(一)以后不能重分类进损益表的其他综合收益',
    remearsured_other_income float comment '1.1 重新计量设定收益计划净负债或净资产的变动',
    other_income_equity_unclassified_income_statement float comment '1.2 权益法下在被投资单位不能重分类进损益表的其他综合收益中享有的份额',
    other_equity_instruments_change float comment '1.3 其他权益工具投资公允价值变动',
    corporate_credit_risk_change float comment '1.4 企业自身信用风险公允价值变动',
    other_income_classified_income_statement float comment '(二)以后能重分类进损益表的其他综合收益',
    other_income_equity_classified_income_statement float comment '2.1 权益法下在被投资单位能重分类进损益表的其他综合收益中享有的份额',
    financial_asset_available_for_sale_change float comment '2.2 可供出售金融资产公允价值变动损益',
    financial_asset_hold_to_maturity_change float comment '2.3 持有至到期投资重分类为可供出售金融资产损益',
    cash_flow_hedging_effective_portion float comment '2.4 现金流量套期损益的有效部分',
    foreign_currency_statement_converted_difference float comment '2.5 外币财务报表分析折算差额',
    others float comment '2.6 其他',
    other_debt_investment_change float comment '2.7 其他债权投资公允价值变动',
    assets_reclassified_other_income float comment '2.8 金融资产重分类计入其他综合收益的金额',
    other_debt_investment_reserve float comment '2.9 其他债权投资信用减值准备',
    other_income_minority float comment '归属于少数股东的其他综合收益总额',
    total_income float comment '综合收益总额',
    total_income_parent_company float comment '归属于母公司所有者的综合收益总额',
    total_income_minority float comment '归属于少数股东的综合收益总额',
    basic_earnings_per_share float comment '基本每股收益',
    fully_diluted_earnings_per_share float comment '稀释每股收益',
    report_date varchar(30) comment '报表日期'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 comment '利润表';







